name: hldsp@Feizao

on:
  workflow_dispatch:
  schedule:
    - cron: '20 5,18 * * *'
  # 本地时间+8
  watch:
    types: started
  repository_dispatch:
    types: hldsp
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行 【哈喽短视频】'
        run: |
          node Task/hldsp.js
        env:
          HLDSPURL: ${{ secrets.HLDSPURL }}
          HLDSPHD: ${{ secrets.HLDSPHD }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
